# Development profile
# Use Dockerfile-compatible environment variable names with local defaults.
###    JDBC : SGDB :// HOST : PORT / DB
# DATABASE_NAME=safestepdb_k99s
# DATABASE_URL=dpg-d8pj85v7f7vs73d1r4i0-a.oregon-postgres.render.com
# spring.datasource.url=jdbc:postgresql://safestepdbuser:JNl8lKp0oALTwGpYKnlvSexSBRXLX8Zl@dpg-d8pj85v7f7vs73d1r4i0-a.oregon-postgres.render.com/safestepdb_k99s
# spring.datasource.url=jdbc:postgresql://${DATABASE_USER:safestepdbuser}:${DATABASE_PASSWORD:JNl8lKp0oALTwGpYKnlvSexSBRXLX8Zl}@${DATABASE_URL:dpg-d8pj85v7f7vs73d1r4i0-a.oregon-postgres.render.com}/${DATABASE_NAME:safestepdb_k99s}
spring.datasource.url=jdbc:postgresql://${DATABASE_URL:dpg-d8pj85v7f7vs73d1r4i0-a.oregon-postgres.render.com}:${DATABASE_PORT:5432}/${DATABASE_NAME:safestepdb_k99s}
# spring.datasource.username=safestepdbuser
spring.datasource.username=${DATABASE_USER:safestepdbuser}
# spring.datasource.password=JNl8lKp0oALTwGpYKnlvSexSBRXLX8Zl
spring.datasource.password=${DATABASE_PASSWORD:JNl8lKp0oALTwGpYKnlvSexSBRXLX8Zl}

# Developer-friendly JPA behavior
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# App port
# server.port=8092
server.port=${PORT:8092}
